"use client"

import * as React from "react"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { Edit2 } from "lucide-react"
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { transactionSchema, type TransactionFormValues } from "@/lib/validations"
import { editTransaction } from "@/features/transactions/actions"
import { useRouter } from "next/navigation"
import { AssetTransactionForm } from "./asset-transaction-form"
import { Transaction } from "@prisma/client"

interface EditTransactionModalProps {
  transaction: Transaction;
  asset: {
    symbol: string;
    name: string;
    assetClass: TransactionFormValues["assetClass"];
    currency: "VND" | "USD";
    termDeposit?: {
      interestRate: number;
      maturityDate: Date | string;
      resolvedAt?: Date | string | null;
    };
  };
  fxRate?: number;
}

/**
 * Modal wrapper for editing an existing asset transaction.
 * Uses the shared AssetTransactionForm for UI.
 */
export function EditTransactionModal({ 
  transaction, 
  asset, 
  fxRate = 25400 
}: EditTransactionModalProps) {
  const [open, setOpen] = React.useState(false)
  const [isSubmitting, setIsSubmitting] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)
  const router = useRouter()

  const isConversion = !!transaction.conversionId
  const isResolvedTD = asset.assetClass === 'TERM_DEPOSIT' && !!asset.termDeposit?.resolvedAt

  // Derive fees from gross amount since they aren't stored explicitly
  const theoreticalValueVnd = Math.abs(transaction.quantity * transaction.pricePerUnit)
  const actualValueVnd = Math.abs(transaction.grossAmount)
  const derivedFeeVnd = transaction.type === 'BUY' 
    ? actualValueVnd - theoreticalValueVnd 
    : theoreticalValueVnd - actualValueVnd
  const initialFeesVnd = Math.max(0, derivedFeeVnd)
  const initialFees = asset.currency === 'USD' ? initialFeesVnd / fxRate : initialFeesVnd

  const form = useForm<TransactionFormValues>({
    resolver: zodResolver(transactionSchema),
    defaultValues: {
      symbol: asset.symbol,
      name: asset.name,
      assetClass: asset.assetClass,
      type: transaction.type as TransactionFormValues["type"],
      quantity: transaction.quantity,
      price: asset.currency === 'USD' ? transaction.pricePerUnit / fxRate : transaction.pricePerUnit,
      fees: initialFees,
      currency: asset.currency,
      date: new Date(transaction.date).toISOString().split('T')[0],
      interestRate: asset.termDeposit?.interestRate,
      maturityDate: asset.termDeposit?.maturityDate 
        ? new Date(asset.termDeposit.maturityDate).toISOString().split('T')[0] 
        : undefined,
    },
  })

  async function onSubmit(data: TransactionFormValues) {
    if (isConversion || isResolvedTD) {
      setError(isConversion 
        ? "Conversion-linked transactions cannot be edited directly." 
        : "Transactions for resolved term deposits are locked."
      )
      return
    }

    setIsSubmitting(true)
    setError(null)
    try {
      const result = await editTransaction(transaction.id, data)
      if (result.success) {
        setOpen(false)
        router.refresh()
      } else {
        setError(result.error || "Failed to update transaction")
      }
    } catch (err) {
      console.error(err)
      setError("An unexpected error occurred")
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button 
          variant="ghost" 
          size="icon" 
          className="h-8 w-8 text-slate-500 hover:text-emerald-400 hover:bg-emerald-400/10"
        >
          <Edit2 className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px] glass-premium border-white/10">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold text-white">Edit Transaction</DialogTitle>
        </DialogHeader>
        
        {(isConversion || isResolvedTD) && (
          <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 mb-4 animate-in fade-in slide-in-from-top-2">
            <p className="text-xs text-blue-400 leading-relaxed font-medium">
              {isConversion 
                ? "This transaction was generated by an asset conversion. It can be viewed but not edited directly to maintain accounting integrity."
                : "This term deposit has been resolved. Past transactions are locked to prevent historical P&L mismatches."}
            </p>
          </div>
        )}

        <form onSubmit={form.handleSubmit(onSubmit)} className="py-4">
          <AssetTransactionForm
            form={form}
            mode="edit"
            error={error}
            isSubmitting={isSubmitting}
            fxRate={fxRate}
            submitLabel="Update Transaction"
          />
        </form>
      </DialogContent>
    </Dialog>
  )
}
